name: Test3
announcement_mode: telegram
telegram:
  token: "test"
  chat_id: 0
secret_key: almafa

server:
  port: 4244

nodes:
  test1:
    name: "Test1"
    address: "http://localhost:4242"
  test2:
    name: "Test2"
    address: "http://localhost:4243"
  test3:
    name: "Test3"
    address: "http://localhost:4244"
