name: Test1
telegram_token: "test"
telegram_chat_id: 0
announcement_mode: log
secret_key: almafa
poll_time: 10s
webui_enabled: true

server:
  host: "localhost:4242"
  ssl: false

nodes:
  - name: "Test1"
    address: "http://localhost:4242"
  - name: "Test2"
    address: "http://localhost:4243"
  - name: "Test3"
    address: "http://localhost:4244"
