# yaml-language-server: $schema=config.schema.json

name: Test1
announcement_mode: log
secret_key: almafa
poll_time: 10s
webui_enabled: true

server:
  ip_address: "0.0.0.0"
  port: 4242
  ssl: null

nodes:
  test1:
    name: "Test1"
    address: "http://localhost:4242"
  test2:
    name: "Test2"
    address: "http://localhost:4243"
  test3:
    name: "Test3"
    address: "http://localhost:4244"
