name: Test2
announcement_mode: log
secret_key: almafa

server:
  port: 4243
  ssl:
    cert_path: "./keys/certificate.pem"
    key_path: "./keys/private_key.pkcs.pem"

nodes:
  test1:
    name: "Test1"
    address: "http://localhost:4242"
  test2:
    name: "Test2"
    address: "http://localhost:4243"
  test3:
    name: "Test3"
    address: "http://localhost:4244"
