name: Test2
telegram_token: "test"
telegram_chat_id: 0

server:
  host: "localhost:4243"
  cert_path: "./keys/certificate.pem"
  key_path: "./keys/private_key.pkcs.pem"

nodes:
  - name: "Test1"
    telegram_handle: "Dewyer"
    address: "https://localhost:4242"
  - name: "Test3"
    address: "https://localhost:4244"
