services:
  freecaster-grid-1:
    image: freecaster-grid
    container: freecaster-grid
    restart: on-failure:3
    volumes:
      - /path/to/config:/config/config.yaml
      - /path/to/keys:/keys
    porst:
      - 4242:4242
