services:
  freecaster-grid:
    image: ghcr.io/dewyer/freecaster-grid:latest
    container_name: freecaster-grid
    restart: unless-stopped
    volumes:
      - /path/to/config:/config/config.yaml
      - /path/to/keys:/keys
    ports:
      - 4242:4242
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_ENABLED=true
