name: Manual Release
on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version increment to apply"
        required: true
        default: patch
        type: choice
        options: [major, minor, patch]
      dry_run:
        description: "Dry run (no tag push or release creation)"
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  gather_info:
    name: Gather info for release
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      new_tag: ${{ steps.version.outputs.new_tag }}
      version_update_needed: ${{ steps.check_version.outputs.version_update_needed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v5
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Compute next version
        id: version
        shell: bash
        run: |
          set -euo pipefail
          bump="${{ github.event.inputs.bump }}"

          # Get latest semver tag (supports vX.Y.Z or X.Y.Z). Defaults to 0.0.0 if none.
          mapfile -t tags < <(git tag -l 'v[0-9]*.[0-9]*.[0-9]*' '[0-9]*.[0-9]*.[0-9]*' | sed 's/^v//' | sort -V)
          latest="0.0.0"
          if (( ${#tags[@]} > 0 )); then
            latest="${tags[-1]}"
          fi

          IFS='.' read -r major minor patch <<<"$latest"
          case "$bump" in
            major)
              major=$((major + 1)); minor=0; patch=0;;
            minor)
              minor=$((minor + 1)); patch=0;;
            patch)
              patch=$((patch + 1));;
            *) echo "Invalid bump type: $bump" >&2; exit 1;;
          esac

          new_version="${major}.${minor}.${patch}"
          echo "new_version=${new_version}" >> "$GITHUB_OUTPUT"
          echo "new_tag=v${new_version}" >> "$GITHUB_OUTPUT"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false

      - name: Check version in Cargo.toml
        shell: bash
        id: check_version
        run: echo "version_update_needed=$(uv run scripts/check_cargo_version.py ${{ steps.version.outputs.new_version }})" >> "$GITHUB_OUTPUT"

  dry_run_release:
    if: ${{ github.event.inputs.dry_run == 'true' }}
    name: Perform dry run or actual release
    needs: gather_info
    runs-on: ubuntu-latest
    steps:
      - name: Dry run preview
        run: |
          echo "Dry run mode enabled: no tag or release will be created."
          echo "Target branch: ${{ github.ref_name }}"
          echo "Computed next tag: ${{ needs.gather_info.outputs.new_tag }}"
          echo "Cargo.toml version update needed: ${{ needs.gather_info.outputs.version_update_needed }}"

  update_version:
    if: ${{ github.event.inputs.dry_run == 'false' && needs.gather_info.outputs.version_update_needed == 'true'}}
    name: Update version in Cargo.toml and create PR
    needs: gather_info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Cargo.toml
            scripts/update_cargo_version.py

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false

      - name: Update version in Cargo.toml
        shell: bash
        run: uv run scripts/update_cargo_version.py ${{ needs.gather_info.outputs.new_version }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        id: create_pr
        with:
          commit-message: "chore: Bump version to ${{ needs.gather_info.outputs.new_version }}"
          title: "Bump version to ${{ needs.gather_info.outputs.new_version }}"
          body: |
            This PR bumps the version in Cargo.toml to ${{ needs.gather_info.outputs.new_version }}.
          draft: false
          delete-branch: true

  build_docker_image:
    if: ${{ github.event.inputs.dry_run == 'false' && needs.gather_info.outputs.version_update_needed == 'false'}}
    name: Build Docker image for updated version
    needs: gather_info
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build_image.outputs.image_tag }}
    steps:
      - name: Build and push Docker image
        uses: Dewyer/freecaster-grid/.github/workflows/docker-publish.yml@main
        id: build_image
        with:
          tag: ${{ needs.gather_info.outputs.new_tag }}

  build_release:
    if: ${{ github.event.inputs.dry_run == 'false' && needs.gather_info.outputs.version_update_needed == 'false'}}
    needs: gather_info
    name: Build release artifacts on ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            rust_target: x86_64-unknown-linux-musl
          - os: ubuntu-24.04-arm
            arch: arm64
            rust_target: aarch64-unknown-linux-musl
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.rust_target }}

      - name: Install musl dependencies
        run: sudo apt-get update && sudo apt-get install -y musl-dev musl-tools

      - name: Install build dependencies
        run: cargo build --target ${{ matrix.rust_target }} --release

      - name: Create release artifacts
        id: create_artifacts
        run: |
          set -euo pipefail
          mkdir -p artifacts
          cp "target/${{ matrix.rust_target }}/release/freecaster-grid" "artifacts/freecaster-grid-${{ matrix.arch }}"
          chmod +x "artifacts/freecaster-grid-${{ matrix.arch }}"
          tar -czvf "artifacts/freecaster-grid-${{ matrix.arch }}.tar.gz" -C artifacts "freecaster-grid-${{ matrix.arch }}"
          sha256sum "artifacts/freecaster-grid-${{ matrix.arch }}.tar.gz" > "artifacts/freecaster-grid-${{ matrix.arch }}.tar.gz.sha256"

      - name: List artifacts
        run: ls -l artifacts
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "release-artifacts-${{ matrix.arch }}"
          path: |
            artifacts/freecaster-grid-${{ matrix.arch }}.tar.gz
            artifacts/freecaster-grid-${{ matrix.arch }}.tar.gz.sha256

  perform-release:
    if: ${{ github.event.inputs.dry_run != 'true' && needs.gather_info.outputs.version_update_needed == 'false'}}
    name: Perform Release
    needs:
      - gather_info
      - build_docker_image
      - build_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: release-artifacts-*
          path: artifacts

      - name: Tag and push tag
        shell: bash
        run: |
          set -euo pipefail
          tag="${{ needs.gather_info.outputs.new_tag }}"

          if git rev-parse -q --verify "refs/tags/${tag}" >/dev/null; then
            echo "Tag ${tag} already exists. Aborting." >&2
            exit 1
          fi

          git tag -a "${tag}" -m "Release ${tag}"
          git push origin "${tag}"

      - name: Create release with generated notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.gather_info.outputs.new_tag }}
          name: ${{ needs.gather_info.outputs.new_tag }}
          generate_release_notes: true
          draft: true
          body: |
            > This is a draft release for version ${{ needs.gather_info.outputs.new_tag }}.
            > Please review the release notes and publish when ready.

            Docker image is available at:
            ```
            ${{ needs.build_docker_image.outputs.image_tag }}
            ```
          files: artifacts/*

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
