name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
        include:
          - cargo_cmd: build
            name: Build
          - cargo_cmd: test
            name: Test
          - cargo_cmd: fmt -- --check
            name: Format
          - cargo_cmd: clippy -- -D warnings
            name: Clippy
          - cargo_cmd: +nightly udeps --all-targets --all-features
            name: Unused Dependencies
        
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.name == 'Unused Dependencies' && 'nightly' || null }}
      - uses: taiki-e/install-action@cargo-udeps
        name: Install cargo-udeps
        if: matrix.name == 'Unused Dependencies'
      - name: Build
        run: cargo ${{ matrix.cargo_cmd }}
